name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    runs-on: ubuntu-latest
    env:
      BACKEND_BASE_URL: http://localhost:7777
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend
        run: make install-backend

      - name: Test
        run: make test

      - name: Lint
        run: make lint
